### ISSUE TITLE
Add to Galaxy: user?

### ISSUE THREAD

**Issue by ctorgalson** [ChromaticHQ/ansible-role-aws-cli#3]
@markdorison: I couldn't find `ChromaticHQ` or any similar variant on Galaxy to add this to.

**Comment by markdorison** [comment]
@ctorgalson I logged in to Galaxy with my Github credentials and at [this url](https://galaxy.ansible.com/roleadd#/) I see a number of our ansible repos that we can enable, but not this particular one. 🤔 

<img width="946" alt="screenshot 2017-12-15 09 28 26" src="https://user-images.githubusercontent.com/20355/34046230-54f2f848-e17a-11e7-8a8c-20b4240f6ce5.png">

**Comment by ctorgalson** [comment]
@markdorison: Ah, I didn't realize that *I* could do it. I got it into the list with a refresh, thanks.
